version: "3"

networks:
  main:
    driver: overlay
    attachable: true

volumes:
  npm_data:
    driver: local
  gitea_data:
    driver: local
  drone_data:
    driver: local
  portainer_data:
    driver: local

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    volumes:
      - npm_data:/data
    ports:
      - "80:80"   # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81"   # Admin Web Port
    networks:
      - main

  gitea:
    image: gitea/gitea:1.15.8
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
    networks:
      - main

  droneCI:
    image: drone/drone:2
    environment:
      - DRONE_GITHUB_SKIP_VERIFY=true
      - DRONE_AGENTS_ENABLED=true
      - DRONE_SERVER_HOST=http://drone.master.develop
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_OPEN=false
      - DRONE_GITEA=true
      - DRONE_GITEA_SERVER=http://gitea.master.develop
      - DRONE_GITEA_CLIENT_ID=
      - DRONE_GITEA_CLIENT_SECRET=
      - DRONE_RPC_SECRET=5ae672423a922d3b7bd1cde3fc993f3d
    volumes:
      - drone_data:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 6000:80
      - 7000:443
    networks:
      - main
  
  droneCI-runner:
    image: drone/drone-runner-docker:1
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone.master.develop
      - DRONE_RPC_SECRET=5ae672423a922d3b7bd1cde3fc993f3d
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=dockerbuil-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5000:3000
    networks:
      - main

  portainer:
    image: portainer/portainer-ce:2.11.0
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - main

  agent:
    image: portainer/agent:2.11.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - main
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
