version: "3"

volumes:
  portainer_data:
    driver: local
  gitea_data:
    driver: local
  drone_data:
    driver: local

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./reverse-proxy/ingress.conf:/etc/nginx/nginx.conf
    depends_on:
      - portainer
      - gitea
      - drone
    ports:
      - "80:80"   # Public HTTP Port

  gitea:
    image: gitea/gitea:1.15.8
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"

  droneCI:
    image: drone/drone:2
    ports:
      - 6000:80
      - 7000:443
    volumes:
      - drone_data:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_GITHUB_SKIP_VERIFY=true
      - DRONE_AGENTS_ENABLED=true
      - DRONE_SERVER_HOST=http://192.168.56.100:888
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_OPEN=false
      - DRONE_GITEA=true
      - DRONE_GITEA_SERVER=http://192.168.56.100:3000
      - DRONE_GITEA_CLIENT_ID=9360a368-dc27-4448-8ae7-8107cf430286
      - DRONE_GITEA_CLIENT_SECRET=iQWo7fN6O9d1iYzOrM3QdkdMdwsI07O5AzjMtFvxpc5i
      - DRONE_RPC_SECRET=5ae672423a922d3b7bd1cde3fc993f3d
