version: "3"

volumes:
  npm_data:
    driver: local
  gitea_data:
    driver: local
  drone_data:
    driver: local
  portainer_data:
    driver: local

services:
  #nginx:
  #  image: 
  #  build:
  #    context: .
  #    dockerfile: ./reverse-proxy/Dockerfile
  #  depends_on:
  #    - portainer
  #    - gitea
  #    - drone
  #  ports:
  #    - "80:80"   # Public HTTP Port
  npm:
    image: jc21/nginx-proxy-manager:latest
    ports:
      # These ports are in format <host-port>:<container-port>
      - "80:80"   # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81"   # Admin Web Port
    volumes:
      - npm_data:/data

  gitea:
    image: gitea/gitea:1.15.8
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"

  droneCI:
    image: drone/drone:2
    ports:
      - 6000:80
      - 7000:443
    volumes:
      - drone_data:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_GITHUB_SKIP_VERIFY=true
      - DRONE_AGENTS_ENABLED=true
      - DRONE_SERVER_HOST=http://drone.localdev
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_OPEN=false
      - DRONE_GITEA=true
      - DRONE_GITEA_SERVER=http://gitea.localdev
      - DRONE_GITEA_CLIENT_ID=9360a368-dc27-4448-8ae7-8107cf430286
      - DRONE_GITEA_CLIENT_SECRET=iQWo7fN6O9d1iYzOrM3QdkdMdwsI07O5AzjMtFvxpc5i
      - DRONE_RPC_SECRET=5ae672423a922d3b7bd1cde3fc993f3d

  portainer:
    image: portainer/portainer-ce:2.11.0
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  agent:
    image: portainer/agent:2.11.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
